import type { Metadata } from "next";
import "./globals.css";
import {NavbarLayout} from "@/app/commonComponents/NavbarLayout";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={"h-screen"}  data-theme={"cupcake"}>

      <body
        className={`h-full`}
      >
     <NavbarLayout>
         {children}
     </NavbarLayout>
      </body>
    </html>
  );
}
